// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB7pt_X0hV9r8E3doo4oS4a10-A54v8s0',
    appId: '1:352651126765:web:e6f6a250183ac688c629e4',
    messagingSenderId: '352651126765',
    projectId: 'farmerconnect-e7fc0',
    authDomain: 'farmerconnect-e7fc0.firebaseapp.com',
    storageBucket: 'farmerconnect-e7fc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2p4QEsulqntm2boHiiYnNWJLyOnqQDIs',
    appId: '1:352651126765:android:d87fe891b7d4aafcc629e4',
    messagingSenderId: '352651126765',
    projectId: 'farmerconnect-e7fc0',
    storageBucket: 'farmerconnect-e7fc0.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB7pt_X0hV9r8E3doo4oS4a10-A54v8s0',
    appId: '1:352651126765:web:d82124b8d25b7d09c629e4',
    messagingSenderId: '352651126765',
    projectId: 'farmerconnect-e7fc0',
    authDomain: 'farmerconnect-e7fc0.firebaseapp.com',
    storageBucket: 'farmerconnect-e7fc0.appspot.com',
  );

}